name: Terraform apply

on: 
    workflow_run:
        workflows: ["Terraform plan"] # Trigger this workflow when the "Terraform plan" workflow completes
        types:
            - completed


jobs:
    Apply:
        if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if the plan was successful
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.6.6

            - name: configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Terraform Init
              working-directory: ./Terraform
              run: terraform init

            - name: Terraform Apply
              working-directory: ./Terraform
              run: |
               terraform apply -auto-approve
               aws eks update-kubeconfig --name production-eks-cluster --region ${{ secrets.AWS_REGION }}

            - name: Apply cluster issuer
              working-directory: ./cert-man
              run: |
                kubectl apply -f cluster-issuer.yaml


            - name: Apply app manifest
              working-directory: ./argo-cd/app
              run: |
                kubectl apply -f app.yaml

            - name: Apply ArgoCD values
              working-directory: ./argo-cd
              run: |
                kubectl apply -f argocd.yaml
