name: Terraform destroy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: type 'destroy' to destroy
        required: true
        default: 'no'


jobs:
    destroy:
        name: Destroy infrastructure
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout code
          uses: actions/checkout@v2
                
        - name: Abort if Not Confirmed
          if: ${{ github.event.inputs.confirmation != 'destroy' }}  # Runs for any input other than 'destroy'
          run: |
             echo "Workflow is aborted because you did not say 'destroy'."
             exit 1 # Exit with a non-zero status to fail the job

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
           terraform_version: 1.11.1

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}


        - name: Terraform init
          working-directory: ./Terraform # Specify the directory where your Terraform files are located
          run: terraform init


        - name: Terraform validate
          working-directory: ./Terraform # Specify the directory where your Terraform files are located
          run: terraform validate

        - name: Terraform destroy # This step will only run if the confirmation input is 'destroy'
          working-directory: ./Terraform # Specify the directory where your Terraform files are located
          run: terraform destroy -auto-approve # Automatically approve the destroy step
    
