name: Terraform plan

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: type 'plan' to confirm
        required: true
        default: 'no'

jobs:
  Lint:
    name: Tflint 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Abort if Not Confirmed
        if: ${{ github.event.inputs.confirmation != 'plan' }}
        run: |
          echo "Workflow is aborted because you did not say 'plan'."
          exit 1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.1

      - name: set up Tflint
        uses: terraform-linters/setup-tflint@master
        with: 
          tflint_version: latest

      - name: Run Tflint
        working-directory: ./Terraform
        run: tflint --recursive
        continue-on-error: true

  Checkov:
    name: Checkov scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Checkov
        run: |
          pip install checkov
          echo "Checkov installed successfully"

      - name: Run Checkov
        working-directory: ./Terraform
        run: |
          checkov -d . --quiet --soft-fail
          echo "Checkov scan completed successfully"


  TerraformPlan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.1

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./Terraform
        run: terraform init

      - name: Terraform fmt
        working-directory: ./Terraform
        run: terraform fmt

      - name: Terraform Validate
        working-directory: ./Terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./Terraform
        run: terraform plan
 